<?php

namespace App\Models;

use App\Enums\OrderProductState;
use App\Enums\OrderState;
use App\Enums\OutgoingState;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Http;

class OrderProduct extends Model
{
    use HasFactory;

    protected $table = "order_product";


    protected $fillable = [
        "state",
        "order_id",
        "product_id",
        "accept",
        "partner",
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function review()
    {
        return $this->hasOne(Review::class);
    }

}
